modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="modern_crayfish" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Modern Crayfish" #mandatory
logoFile="modern_crayfish.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional
description='''

'''

[[dependencies.modern_crayfish]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.modern_crayfish]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.modern_crayfish]]
    modId="cfm"
    mandatory=true
    versionRange="[7.0.0-pre22,)"
    ordering="AFTER"
    side="BOTH"